// <auto-generated />
using System;
using FindMyMeds.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindMyMeds.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206105630_SeedMedications")]
    partial class SeedMedications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindMyMeds.Core.Entities.AvailabilityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyMedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyMedicationId");

                    b.ToTable("AvailabilityLogs");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicationCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicationCategoryId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "GSK",
                            Name = "Panadol"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Abbott",
                            Name = "Brufen"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "GSK",
                            Name = "Augmentin"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Bayer",
                            Name = "Aspirin"
                        });
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.MedicationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicationCategories");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.MedicationSubstitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlternativeMedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryMedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeMedicationId");

                    b.HasIndex("PrimaryMedicationId");

                    b.ToTable("MedicationSubstitutes");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.PharmacyMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyMedications");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.PharmacyStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyStaffs");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.UserSearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserSearchLogs");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.AvailabilityLog", b =>
                {
                    b.HasOne("FindMyMeds.Core.Entities.PharmacyMedication", "PharmacyMedication")
                        .WithMany()
                        .HasForeignKey("PharmacyMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmacyMedication");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.Medication", b =>
                {
                    b.HasOne("FindMyMeds.Core.Entities.MedicationCategory", "Category")
                        .WithMany("Medications")
                        .HasForeignKey("MedicationCategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.MedicationSubstitute", b =>
                {
                    b.HasOne("FindMyMeds.Core.Entities.Medication", "AlternativeMedication")
                        .WithMany("AsAlternativeSubstitutes")
                        .HasForeignKey("AlternativeMedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindMyMeds.Core.Entities.Medication", "PrimaryMedication")
                        .WithMany("AsPrimarySubstitutes")
                        .HasForeignKey("PrimaryMedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlternativeMedication");

                    b.Navigation("PrimaryMedication");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.PharmacyMedication", b =>
                {
                    b.HasOne("FindMyMeds.Core.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindMyMeds.Core.Entities.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyMedications")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.PharmacyStaff", b =>
                {
                    b.HasOne("FindMyMeds.Core.Entities.Pharmacy", "Pharmacy")
                        .WithMany("Staff")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.Medication", b =>
                {
                    b.Navigation("AsAlternativeSubstitutes");

                    b.Navigation("AsPrimarySubstitutes");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.MedicationCategory", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("FindMyMeds.Core.Entities.Pharmacy", b =>
                {
                    b.Navigation("PharmacyMedications");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
